### ISSUE TITLE
Dependency to Monolog should be removed and replaced by the NullLogger from psr/log

### ISSUE THREAD

**Issue by temp** [alchemy-fr/BinaryDriver#13]
It's only used for the NullHandler, instead a the NullLogger from psr/log can be used.

**Comment by andysnell** [comment]
Hello -- can we bump this issue?  Monolog has a new major version in beta that is not covered by this project's defined dependency.  This is holding back a project I am currently working on.  After reviewing the code, there doesn't seem to be a good reason to default to falling back to a `monolog` instance with a `NullHandler` when the PSR `NullLogger` would do.  It looks like temp already did the work in the above referenced PR.

**Comment by jens1o** [comment]
Hey, I'm sorry, I wasn't aware of that particular pull request. I will look into the PR as soon as possible, however not before next week.

In general, there is a lot of chances to do here. :)

**Comment by ibrahim-mubarak** [comment]
Any updates on this.
We're also stuck due to this.

**Comment by andysnell** [comment]
Hello -- this has been outstanding for three years and was bumped in July.  It's become an issue because Monolog has moved on, but this library is unnecessarily dependent on it. Can we get a will-fix/won't-fix here?  I need to know if we need to move to a different solution and/or if this library will be supported in the future.

**Comment by mojimich2015** [comment]
Any updates on this .

**Comment by jens1o** [comment]
New release (5.1.1) is out with the patch. I'm sorry for the long wait.
